### ISSUE TITLE
초기 세팅 다시 확인해주세요

### ISSUE THREAD

**Issue by soheon-lee** [wecode-bootcamp-korea/10-Oh29-ya-backend#1]
1. settings.py 에 allowed_hosts 모두 허용 해주세요

**Comment by minho-lee0716** [comment]
저희 프로젝트를 로컬에서 진행하나요? 호스트를 누구로 해야할지 아니면 그냥 *만 하면 되는건지 모르겠습니다.

**Comment by soheon-lee** [comment]
`*` 하시면 됩니다 :)

**Comment by soheon-lee** [comment]
민호님 string 처리는 해주셔야 합니다.
ALLOWED_HOSTS = [`'*'`]
